import type { Product } from "./shopify/types";

// Static fallback products when Shopify API is not yet connected
export const STATIC_PRODUCTS: Product[] = [
  {
    id: "1",
    title: "Barbeque Coated Peanut Crackle",
    handle: "barbeque-coated-peanut-crackle",
    description: "A crunchy, flavour-packed plant-based snack made with peanuts, rice flour, and barbeque spices.",
    descriptionHtml: "<p>A crunchy, flavour-packed plant-based snack made with peanuts, rice flour, and barbeque spices.</p><ul><li>No Maida</li><li>No Palm Oil</li><li>Baked and Not Fried</li><li>Gluten Free</li><li>No Preservatives</li><li>Absolutely Healthy for Kids</li><li>Low Glycemic Index</li><li>No Artificial Colors or Additives</li><li>100% Natural</li></ul>",
    productType: "Snacks",
    tags: ["baked", "plant-based", "peanut", "gluten-free", "no-maida", "no-palm-oil", "bestseller"],
    vendor: "The Whole Soul",
    price: { amount: "299.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-peanut.png", altText: "Barbeque Coated Peanut Crackle", width: 800, height: 1000 }],
    variants: [{ id: "v1", title: "Default", availableForSale: true, quantityAvailable: 12, price: { amount: "299.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Barbeque Coated Peanut Crackle", description: "" },
    availableForSale: true,
  },
  {
    id: "2",
    title: "Baked Beetroot Chips",
    handle: "baked-beetroot-chips",
    description: "Crispy baked chips made with real beetroot, udad dal, and a blend of spices.",
    descriptionHtml: "<p>Crispy baked chips made with real beetroot, udad dal, and a blend of spices. Only the good stuff.</p><ul><li>No Maida</li><li>No Palm Oil</li><li>Baked and Not Fried</li><li>No Preservatives</li><li>Real Beetroot Goodness</li><li>Absolutely Healthy for Kids</li><li>No Gluten</li><li>High Nutrition</li></ul>",
    productType: "Snacks",
    tags: ["baked", "chips", "beetroot", "gluten-free", "no-maida", "no-palm-oil"],
    vendor: "The Whole Soul",
    price: { amount: "249.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/hero-beetroot.png", altText: "Baked Beetroot Chips", width: 800, height: 1000 }],
    variants: [{ id: "v2", title: "Default", availableForSale: true, quantityAvailable: 15, price: { amount: "249.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Baked Beetroot Chips", description: "" },
    availableForSale: true,
  },
  {
    id: "3",
    title: "Baked Broccoli Chips",
    handle: "baked-broccoli-chips",
    description: "Light and crispy baked chips made with real broccoli.",
    descriptionHtml: "<p>Light and crispy baked chips made with real broccoli. A deliciously healthy way to snack.</p><ul><li>Gluten Free</li><li>Vegan</li><li>No Preservatives</li><li>No Palm Oil</li><li>Baked and Not Fried</li><li>No Artificial Colors or Additives</li></ul>",
    productType: "Snacks",
    tags: ["baked", "chips", "broccoli", "vegan", "gluten-free", "no-palm-oil"],
    vendor: "The Whole Soul",
    price: { amount: "249.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-broccoli.png", altText: "Baked Broccoli Chips", width: 800, height: 1000 }],
    variants: [{ id: "v3", title: "Default", availableForSale: true, quantityAvailable: 11, price: { amount: "249.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Baked Broccoli Chips", description: "" },
    availableForSale: true,
  },
  {
    id: "4",
    title: "Pure Chocolate Coated Date Bites",
    handle: "pure-chocolate-coated-date-bites",
    description: "Indulgent date bites coated in pure chocolate, made with real almonds, dates, and pure ghee.",
    descriptionHtml: "<p>Indulgent date bites coated in pure chocolate, made with real almonds, dates, and pure ghee. A guilt-free treat.</p><ul><li>Made with Pure Ghee</li><li>Real Almonds and Dates</li><li>No Hidden Additives</li><li>No Added Sugar</li><li>Rich in Fiber</li><li>No Artificial Flavour</li><li>100% Natural</li><li>No Preservatives</li></ul>",
    productType: "Snacks",
    tags: ["chocolate", "dates", "almonds", "no-added-sugar", "natural"],
    vendor: "The Whole Soul",
    price: { amount: "399.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-date-bites.png", altText: "Pure Chocolate Coated Date Bites", width: 800, height: 1000 }],
    variants: [{ id: "v4", title: "Default", availableForSale: true, quantityAvailable: 14, price: { amount: "399.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Pure Chocolate Coated Date Bites", description: "" },
    availableForSale: true,
  },
  {
    id: "5",
    title: "Pure Chocolate Coated Pecan Nuts",
    handle: "pure-chocolate-coated-pecan-nuts",
    description: "Premium pecan nuts coated in pure chocolate.",
    descriptionHtml: "<p>Premium pecan nuts coated in pure chocolate. A rich, indulgent snack that's surprisingly wholesome.</p><ul><li>Super-Rich in Antioxidants</li><li>No Artificial Color or Sweeteners</li><li>No Added Sugar</li><li>100% Natural</li><li>No Preservatives</li></ul>",
    productType: "Snacks",
    tags: ["chocolate", "pecan", "nuts", "no-added-sugar", "natural"],
    vendor: "The Whole Soul",
    price: { amount: "449.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-pecan.png", altText: "Pure Chocolate Coated Pecan Nuts", width: 800, height: 1000 }],
    variants: [{ id: "v5", title: "Default", availableForSale: true, quantityAvailable: 10, price: { amount: "449.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Pure Chocolate Coated Pecan Nuts", description: "" },
    availableForSale: true,
  },
  {
    id: "6",
    title: "Premium Chocolate Coated Raisins",
    handle: "premium-chocolate-coated-raisins",
    description: "Plump, juicy raisins enrobed in rich dark chocolate.",
    descriptionHtml: "<p>Plump, juicy raisins enrobed in rich dark chocolate. A timeless indulgence, redefined. Hand packed with care.</p><ul><li>Dark Chocolate and Plump Raisins</li><li>A Timeless Indulgence Redefined</li><li>Hand Packed with Care</li><li>Premium Gift Jar</li></ul>",
    productType: "Snacks",
    tags: ["chocolate", "raisins", "dark-chocolate", "premium"],
    vendor: "The Whole Soul",
    price: { amount: "499.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-raisins.png", altText: "Premium Chocolate Coated Raisins", width: 800, height: 1000 }],
    variants: [{ id: "v6", title: "Default", availableForSale: true, quantityAvailable: 13, price: { amount: "499.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Premium Chocolate Coated Raisins", description: "" },
    availableForSale: true,
  },
  {
    id: "7",
    title: "Vada Pav Chilla Instant Mix",
    handle: "vada-pav-chilla-instant-mix",
    description: "Bring the iconic vada pav flavour home in a healthy chilla format.",
    descriptionHtml: "<p>Bring the iconic vada pav flavour home in a healthy chilla format. Just add water, cook it on the pan, and enjoy homemade goodness in 4 minutes.</p><ul><li>Just Add Water</li><li>Ready in 4 Minutes</li><li>Cook on the Pan</li><li>Homemade Goodness</li><li>No Artificial Additives</li></ul>",
    productType: "Instant Mix",
    tags: ["instant-mix", "chilla", "vada-pav", "quick-meal", "healthy"],
    vendor: "The Whole Soul",
    price: { amount: "199.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-vadapav.png", altText: "Vada Pav Chilla Instant Mix", width: 800, height: 1000 }],
    variants: [{ id: "v7", title: "Default", availableForSale: true, quantityAvailable: 15, price: { amount: "199.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Vada Pav Chilla Instant Mix", description: "" },
    availableForSale: true,
  },
];

export function getStaticProduct(handle: string): Product | null {
  return STATIC_PRODUCTS.find((p) => p.handle === handle) ?? null;
}
