import type { Product } from "./shopify/types";

// Static fallback products — prices match the latest product list (March 2026)
export const STATIC_PRODUCTS: Product[] = [
  {
    id: "1",
    title: "Barbeque Coated Peanuts",
    handle: "barbeque-coated-peanuts",
    description: "A crunchy, flavour-packed plant-based snack made with peanuts, rice flour, and barbeque spices. Warning: extremely addictive.",
    descriptionHtml: "<p>A crunchy, flavour-packed plant-based snack made with peanuts, rice flour, and barbeque spices. Warning: extremely addictive.</p><ul><li>No Maida</li><li>No Palm Oil</li><li>Baked and Not Fried</li><li>Gluten Free</li><li>No Preservatives</li><li>Absolutely Healthy for Kids</li><li>Low Glycemic Index</li><li>No Artificial Colors or Additives</li><li>100% Natural</li></ul>",
    productType: "Snacks",
    tags: ["baked", "plant-based", "peanut", "gluten-free", "no-maida", "no-palm-oil", "bestseller"],
    vendor: "The Whole Soul",
    price: { amount: "100.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-peanut.jpeg", altText: "Barbeque Coated Peanuts", width: 800, height: 1000 }],
    variants: [{ id: "v1", title: "Default", availableForSale: true, quantityAvailable: 12, price: { amount: "100.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Barbeque Coated Peanuts", description: "Crunchy, plant-based barbeque peanuts. No maida, no palm oil, baked not fried." },
    availableForSale: true,
  },
  {
    id: "2",
    title: "Baked Beetroot Chips",
    handle: "baked-beetroot-chips",
    description: "Crispy baked chips made with real beetroot, urad dal, and a blend of spices. Only the good stuff.",
    descriptionHtml: "<p>Crispy baked chips made with real beetroot, urad dal, and a blend of spices. Only the good stuff.</p><ul><li>No Maida</li><li>No Palm Oil</li><li>Baked and Not Fried</li><li>No Preservatives</li><li>Real Beetroot Goodness</li><li>Absolutely Healthy for Kids</li><li>No Gluten</li><li>High Nutrition</li></ul>",
    productType: "Snacks",
    tags: ["baked", "chips", "beetroot", "gluten-free", "no-maida", "no-palm-oil"],
    vendor: "The Whole Soul",
    price: { amount: "70.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-beetroot.jpeg", altText: "Baked Beetroot Chips", width: 800, height: 1000 }],
    variants: [{ id: "v2", title: "Default", availableForSale: true, quantityAvailable: 15, price: { amount: "70.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Baked Beetroot Chips", description: "Crispy baked chips made with real beetroot. Gluten-free, no preservatives." },
    availableForSale: true,
  },
  {
    id: "3",
    title: "Baked Broccoli Chips",
    handle: "baked-broccoli-chips",
    description: "Light and crispy baked chips made with real broccoli. A deliciously healthy way to snack.",
    descriptionHtml: "<p>Light and crispy baked chips made with real broccoli. A deliciously healthy way to snack.</p><ul><li>Gluten Free</li><li>Vegan</li><li>No Preservatives</li><li>No Palm Oil</li><li>Baked and Not Fried</li><li>No Artificial Colors or Additives</li></ul>",
    productType: "Snacks",
    tags: ["baked", "chips", "broccoli", "vegan", "gluten-free", "no-palm-oil"],
    vendor: "The Whole Soul",
    price: { amount: "75.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-broccoli.jpeg", altText: "Baked Broccoli Chips", width: 800, height: 1000 }],
    variants: [{ id: "v3", title: "Default", availableForSale: true, quantityAvailable: 11, price: { amount: "75.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Baked Broccoli Chips", description: "Crispy baked broccoli chips. Vegan, gluten-free, no preservatives." },
    availableForSale: true,
  },
  {
    id: "4",
    title: "Chocolate Coated Date Bites (Pack of 5)",
    handle: "chocolate-coated-date-bites",
    description: "Indulgent date bites coated in pure chocolate, made with real almonds, dates, and pure ghee. Guilt-free? Pretty much.",
    descriptionHtml: "<p>Indulgent date bites coated in pure chocolate, made with real almonds, dates, and pure ghee. Guilt-free? Pretty much.</p><ul><li>Made with Pure Ghee</li><li>Real Almonds and Dates</li><li>No Hidden Additives</li><li>No Added Sugar</li><li>Rich in Fiber</li><li>No Artificial Flavour</li><li>100% Natural</li><li>No Preservatives</li></ul>",
    productType: "Snacks",
    tags: ["chocolate", "dates", "almonds", "no-added-sugar", "natural"],
    vendor: "The Whole Soul",
    price: { amount: "180.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-date-bites.jpeg", altText: "Chocolate Coated Date Bites", width: 800, height: 1000 }],
    variants: [{ id: "v4", title: "Default", availableForSale: true, quantityAvailable: 14, price: { amount: "180.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Chocolate Coated Date Bites", description: "Date bites coated in pure chocolate. No added sugar, 100% natural." },
    availableForSale: true,
  },
  {
    id: "5",
    title: "Pure Chocolate Pecan Nuts",
    handle: "pure-chocolate-pecan-nuts",
    description: "Premium pecan nuts coated in pure chocolate. Rich, indulgent, and surprisingly wholesome.",
    descriptionHtml: "<p>Premium pecan nuts coated in pure chocolate. Rich, indulgent, and surprisingly wholesome.</p><ul><li>Super-Rich in Antioxidants</li><li>No Artificial Color or Sweeteners</li><li>No Added Sugar</li><li>100% Natural</li><li>No Preservatives</li></ul>",
    productType: "Snacks",
    tags: ["chocolate", "pecan", "nuts", "no-added-sugar", "natural"],
    vendor: "The Whole Soul",
    price: { amount: "359.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-pecan.png", altText: "Pure Chocolate Pecan Nuts", width: 800, height: 1000 }],
    variants: [{ id: "v5", title: "Default", availableForSale: true, quantityAvailable: 10, price: { amount: "359.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Pure Chocolate Pecan Nuts", description: "Premium pecan nuts in pure chocolate. No added sugar, 100% natural." },
    availableForSale: true,
  },
  {
    id: "6",
    title: "Vada Pav Flavour Chilla Premix",
    handle: "vada-pav-chilla-premix",
    description: "Bring the iconic vada pav flavour home in a healthy chilla format. Just add water, cook, and enjoy in 4 minutes.",
    descriptionHtml: "<p>Bring the iconic vada pav flavour home in a healthy chilla format. Just add water, cook, and enjoy in 4 minutes.</p><ul><li>Just Add Water</li><li>Ready in 4 Minutes</li><li>Cook on the Pan</li><li>Homemade Goodness</li><li>No Artificial Additives</li></ul>",
    productType: "Instant Mix",
    tags: ["instant-mix", "chilla", "vada-pav", "quick-meal", "healthy"],
    vendor: "The Whole Soul",
    price: { amount: "150.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-vadapav.png", altText: "Vada Pav Flavour Chilla Premix", width: 800, height: 1000 }],
    variants: [{ id: "v6", title: "Default", availableForSale: true, quantityAvailable: 15, price: { amount: "150.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Vada Pav Flavour Chilla Premix", description: "Vada pav flavoured chilla. Ready in 4 minutes, no artificial additives." },
    availableForSale: true,
  },
  {
    id: "7",
    title: "Oats Thecha Cheela Premix",
    handle: "oats-thecha-cheela-premix",
    description: "Spicy Maharashtrian thecha flavour meets wholesome oats. 30 gms protein, just add water and cook on the pan — ready in 4 mins.",
    descriptionHtml: "<p>Spicy Maharashtrian thecha flavour meets wholesome oats. 30 gms protein, just add water and cook on the pan — ready in 4 mins.</p><ul><li>100% Vegan</li><li>Gluten Free</li><li>100% Natural</li><li>30 gms Protein</li><li>Just Add Water & Cook on the Pan</li><li>Ready in 4 Minutes</li><li>Homemade Goodness</li></ul>",
    productType: "Instant Mix",
    tags: ["instant-mix", "chilla", "cheela", "oats", "thecha", "high-protein", "vegan", "gluten-free", "new"],
    vendor: "The Whole Soul",
    price: { amount: "160.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-oats-cheela.jpeg", altText: "Oats Thecha Cheela Premix", width: 800, height: 1000 }],
    variants: [{ id: "v7", title: "200g", availableForSale: true, quantityAvailable: 12, price: { amount: "160.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Oats Thecha Cheela Premix", description: "High-protein oats cheela with Maharashtrian thecha flavour. Vegan, gluten-free, ready in 4 minutes." },
    availableForSale: true,
  },
  {
    id: "8",
    title: "Quinoa Puffs — Dahi Puri Chaat",
    handle: "quinoa-puffs-dahi-puri-chaat",
    description: "Crunchy quinoa puffs in a tangy dahi puri chaat flavour. Rich in fiber, low GI — no maida, no palm oil, no junk.",
    descriptionHtml: "<p>Crunchy quinoa puffs in a tangy dahi puri chaat flavour. Rich in fiber, low GI — no maida, no palm oil, no junk.</p><ul><li>Rich in Fiber</li><li>Low Glycemic Index</li><li>No Maida</li><li>No Palm Oil</li><li>No Preservatives</li><li>Gourmet Collection</li></ul>",
    productType: "Snacks",
    tags: ["quinoa", "puffs", "chaat", "low-gi", "no-maida", "no-palm-oil", "high-fiber", "gourmet", "new"],
    vendor: "The Whole Soul",
    price: { amount: "120.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-quinoa-puffs.jpeg", altText: "Quinoa Puffs — Dahi Puri Chaat", width: 800, height: 1000 }],
    variants: [{ id: "v8", title: "Default", availableForSale: true, quantityAvailable: 10, price: { amount: "120.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Quinoa Puffs — Dahi Puri Chaat", description: "Crunchy quinoa puffs in dahi puri chaat flavour. Rich in fiber, low GI, no junk." },
    availableForSale: true,
  },
  {
    id: "9",
    title: "Multigrain Popped Crisps — Truffle",
    handle: "multigrain-popped-crisps-truffle",
    description: "Light, airy, popped multigrain crisps with a luxurious truffle flavour. Gluten free, plant based, multigrain goodness.",
    descriptionHtml: "<p>Light, airy, popped multigrain crisps with a luxurious truffle flavour. Gluten free, plant based, multigrain goodness.</p><ul><li>Gluten Free</li><li>Plant Based</li><li>Multigrain Goodness</li><li>No Maida</li><li>No Palm Oil</li><li>No Junk</li><li>Gourmet Collection</li></ul>",
    productType: "Snacks",
    tags: ["popped", "crisps", "multigrain", "truffle", "gluten-free", "plant-based", "gourmet", "new"],
    vendor: "The Whole Soul",
    price: { amount: "140.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-multigrain-truffle.jpeg", altText: "Multigrain Popped Crisps — Truffle", width: 800, height: 1000 }],
    variants: [{ id: "v9", title: "Default", availableForSale: true, quantityAvailable: 10, price: { amount: "140.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Multigrain Popped Crisps — Truffle", description: "Popped multigrain crisps with truffle flavour. Gluten free, plant based." },
    availableForSale: true,
  },
  {
    id: "10",
    title: "Premium Chocolate Coated Almonds — Rose Petals",
    handle: "premium-chocolate-coated-almonds-rose-petals",
    description: "Hand-packed premium almonds enrobed in rich dark chocolate, finished with delicate rose petals. A timeless indulgence, redefined.",
    descriptionHtml: "<p>Hand-packed premium almonds enrobed in rich dark chocolate, finished with delicate rose petals. A timeless indulgence, redefined.</p><ul><li>Premium Whole Almonds</li><li>Pure Chocolate Coating</li><li>Real Rose Petals</li><li>No Added Sugar</li><li>Hand-Packed with Care</li><li>Gift-Worthy</li></ul>",
    productType: "Snacks",
    tags: ["chocolate", "almonds", "rose", "premium", "gift", "no-added-sugar", "new"],
    vendor: "The Whole Soul",
    price: { amount: "449.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/lifestyle-chocolate-almonds-jar.jpeg", altText: "Premium Chocolate Coated Almonds with Rose Petals", width: 800, height: 1000 }],
    variants: [{ id: "v10", title: "150g Jar", availableForSale: true, quantityAvailable: 8, price: { amount: "449.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Premium Chocolate Coated Almonds — Rose Petals", description: "Premium almonds in pure chocolate with rose petals. Hand-packed, gift-worthy indulgence." },
    availableForSale: true,
  },
];

export function getStaticProduct(handle: string): Product | null {
  return STATIC_PRODUCTS.find((p) => p.handle === handle) ?? null;
}
