import type { Product } from "./shopify/types";

// Static fallback products — prices match the latest product list (March 2026)
export const STATIC_PRODUCTS: Product[] = [
  {
    id: "1",
    title: "Barbeque Coated Peanuts",
    handle: "barbeque-coated-peanuts",
    description: "A crunchy, flavour-packed plant-based snack made with peanuts, rice flour, and barbeque spices. Warning: extremely addictive.",
    descriptionHtml: "<p>A crunchy, flavour-packed plant-based snack made with peanuts, rice flour, and barbeque spices. Warning: extremely addictive.</p><ul><li>No Maida</li><li>No Palm Oil</li><li>Baked and Not Fried</li><li>Gluten Free</li><li>No Preservatives</li><li>Absolutely Healthy for Kids</li><li>Low Glycemic Index</li><li>No Artificial Colors or Additives</li><li>100% Natural</li></ul>",
    productType: "Snacks",
    tags: ["baked", "plant-based", "peanut", "gluten-free", "no-maida", "no-palm-oil", "bestseller"],
    vendor: "The Whole Soul",
    price: { amount: "100.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-peanut.png", altText: "Barbeque Coated Peanuts", width: 800, height: 1000 }],
    variants: [{ id: "v1", title: "Default", availableForSale: true, quantityAvailable: 12, price: { amount: "100.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Barbeque Coated Peanuts", description: "Crunchy, plant-based barbeque peanuts. No maida, no palm oil, baked not fried." },
    availableForSale: true,
  },
  {
    id: "2",
    title: "Baked Beetroot Chips",
    handle: "baked-beetroot-chips",
    description: "Crispy baked chips made with real beetroot, urad dal, and a blend of spices. Only the good stuff.",
    descriptionHtml: "<p>Crispy baked chips made with real beetroot, urad dal, and a blend of spices. Only the good stuff.</p><ul><li>No Maida</li><li>No Palm Oil</li><li>Baked and Not Fried</li><li>No Preservatives</li><li>Real Beetroot Goodness</li><li>Absolutely Healthy for Kids</li><li>No Gluten</li><li>High Nutrition</li></ul>",
    productType: "Snacks",
    tags: ["baked", "chips", "beetroot", "gluten-free", "no-maida", "no-palm-oil"],
    vendor: "The Whole Soul",
    price: { amount: "70.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-beetroot.png", altText: "Baked Beetroot Chips", width: 800, height: 1000 }],
    variants: [{ id: "v2", title: "Default", availableForSale: true, quantityAvailable: 15, price: { amount: "70.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Baked Beetroot Chips", description: "Crispy baked chips made with real beetroot. Gluten-free, no preservatives." },
    availableForSale: true,
  },
  {
    id: "3",
    title: "Baked Broccoli Chips",
    handle: "baked-broccoli-chips",
    description: "Light and crispy baked chips made with real broccoli. A deliciously healthy way to snack.",
    descriptionHtml: "<p>Light and crispy baked chips made with real broccoli. A deliciously healthy way to snack.</p><ul><li>Gluten Free</li><li>Vegan</li><li>No Preservatives</li><li>No Palm Oil</li><li>Baked and Not Fried</li><li>No Artificial Colors or Additives</li></ul>",
    productType: "Snacks",
    tags: ["baked", "chips", "broccoli", "vegan", "gluten-free", "no-palm-oil"],
    vendor: "The Whole Soul",
    price: { amount: "75.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-broccoli.png", altText: "Baked Broccoli Chips", width: 800, height: 1000 }],
    variants: [{ id: "v3", title: "Default", availableForSale: true, quantityAvailable: 11, price: { amount: "75.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Baked Broccoli Chips", description: "Crispy baked broccoli chips. Vegan, gluten-free, no preservatives." },
    availableForSale: true,
  },
  {
    id: "4",
    title: "Chocolate Coated Date Bites (Pack of 5)",
    handle: "chocolate-coated-date-bites",
    description: "Indulgent date bites coated in pure chocolate, made with real almonds, dates, and pure ghee. Guilt-free? Pretty much.",
    descriptionHtml: "<p>Indulgent date bites coated in pure chocolate, made with real almonds, dates, and pure ghee. Guilt-free? Pretty much.</p><ul><li>Made with Pure Ghee</li><li>Real Almonds and Dates</li><li>No Hidden Additives</li><li>No Added Sugar</li><li>Rich in Fiber</li><li>No Artificial Flavour</li><li>100% Natural</li><li>No Preservatives</li></ul>",
    productType: "Snacks",
    tags: ["chocolate", "dates", "almonds", "no-added-sugar", "natural"],
    vendor: "The Whole Soul",
    price: { amount: "180.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-date-bites.png", altText: "Chocolate Coated Date Bites", width: 800, height: 1000 }],
    variants: [{ id: "v4", title: "Default", availableForSale: true, quantityAvailable: 14, price: { amount: "180.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Chocolate Coated Date Bites", description: "Date bites coated in pure chocolate. No added sugar, 100% natural." },
    availableForSale: true,
  },
  {
    id: "5",
    title: "Pure Chocolate Pecan Nuts",
    handle: "pure-chocolate-pecan-nuts",
    description: "Premium pecan nuts coated in pure chocolate. Rich, indulgent, and surprisingly wholesome.",
    descriptionHtml: "<p>Premium pecan nuts coated in pure chocolate. Rich, indulgent, and surprisingly wholesome.</p><ul><li>Super-Rich in Antioxidants</li><li>No Artificial Color or Sweeteners</li><li>No Added Sugar</li><li>100% Natural</li><li>No Preservatives</li></ul>",
    productType: "Snacks",
    tags: ["chocolate", "pecan", "nuts", "no-added-sugar", "natural"],
    vendor: "The Whole Soul",
    price: { amount: "359.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-pecan.png", altText: "Pure Chocolate Pecan Nuts", width: 800, height: 1000 }],
    variants: [{ id: "v5", title: "Default", availableForSale: true, quantityAvailable: 10, price: { amount: "359.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Pure Chocolate Pecan Nuts", description: "Premium pecan nuts in pure chocolate. No added sugar, 100% natural." },
    availableForSale: true,
  },
  {
    id: "6",
    title: "Vada Pav Flavour Chilla Premix",
    handle: "vada-pav-chilla-premix",
    description: "Bring the iconic vada pav flavour home in a healthy chilla format. Just add water, cook, and enjoy in 4 minutes.",
    descriptionHtml: "<p>Bring the iconic vada pav flavour home in a healthy chilla format. Just add water, cook, and enjoy in 4 minutes.</p><ul><li>Just Add Water</li><li>Ready in 4 Minutes</li><li>Cook on the Pan</li><li>Homemade Goodness</li><li>No Artificial Additives</li></ul>",
    productType: "Instant Mix",
    tags: ["instant-mix", "chilla", "vada-pav", "quick-meal", "healthy"],
    vendor: "The Whole Soul",
    price: { amount: "150.0", currencyCode: "INR" },
    compareAtPrice: null,
    images: [{ url: "/images/product-vadapav.png", altText: "Vada Pav Flavour Chilla Premix", width: 800, height: 1000 }],
    variants: [{ id: "v6", title: "Default", availableForSale: true, quantityAvailable: 15, price: { amount: "150.0", currencyCode: "INR" }, compareAtPrice: null, selectedOptions: [], image: null }],
    options: [],
    seo: { title: "Vada Pav Flavour Chilla Premix", description: "Vada pav flavoured chilla. Ready in 4 minutes, no artificial additives." },
    availableForSale: true,
  },
];

export function getStaticProduct(handle: string): Product | null {
  return STATIC_PRODUCTS.find((p) => p.handle === handle) ?? null;
}
